# Generated by Django 5.1.1 on 2025-05-08 02:12

from django.conf import settings
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Follow = apps.get_model("posts", "Follow")
    db_alias = schema_editor.connection.alias
    Follow.objects.using(db_alias).filter(user=models.F("following")).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_group_alter_comment_options_alter_post_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts', 'ordering': ('-pub_date',)},
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('following')), _negated=True), name='following_is_not_user'),
        ),
    ]
